@startuml gameLoop

class Controller {
    - List<int> turnPlayer
    + void startGame()
    + void endGame()
    - void dealCards()
    - void checkWinner()
    - nextTurn()
    - void startPlayerTurn()
}


class CardController{
    + void checkChoosenCard()
    + void computeCard()
    - void computeSimpleCard()
    - void computeSpecialCard()
}

class PlayerController{
    + void drawCard()
}


'Start_game -> Deal_cards
'Deal_cards -> Next_turn
'
'
'Next_turn -> StartPlayerTurn
'StartPlayerTurn -> Check_choosen_card
'StartPlayerTurn -> Draw_card
'
'Draw_card -> Next_turn
'Check_choosen_card -> StartPlayerTurn : Not Valid
'Check_choosen_card -> ComputeCard : Valid
'
'ComputeCard -> Check_winner
'Check_winner -> End_game : True
'Check_winner -> Next_turn : False






@enduml