@startuml cards

Enum Color{
    RED
    GREEN
    BLUE
    YELLOW
    BLACK
}

Enum CardNumber{
    ZERO
    ONE
    TWO
    THREE
    FOUR
    FIVE
    SIX
    SEVEN
    EIGHT
    NINE
}

interface Card {
    + color : Color
}

interface SimpleCard implements Card {
    + number : CardNumber
}

abstract class SpecialCard implements Card {
}

class ReverseCard extends SpecialCard {}

class ChangeColor extends SpecialCard {}

class SkipCard extends SpecialCard {
    - numberToSkip : Int
}

class DrawTwoCard extends SpecialCard {
}

class WildDraw4Card extends SpecialCard {
}
'class Deck implements List<Card>{
'    + shuffle() : void
'    + draw() : Card
'}
'
'class PlayerHand implements List<Card> {
'    + addCard(Card card) : void
'    + playCard(Card card) : void
'}

@enduml