@startuml cards

Enum Color{
    RED
    GREEN
    BLUE
    YELLOW
    BLACK
}

interface Card {
    + Color color
}

interface SimpleCard implements Card {
}

class SimpleCardImpl implements SimpleCard {
    + int number
}

abstract class SpecialCard implements Card {
}

class ReverseCard extends SpecialCard {}

class ChangeColor extends SpecialCard {}

class SkipCard extends SpecialCard {
    - int numberToSkip
}

class DrawTwoCard extends SpecialCard {
}

class WildDraw4Card extends SpecialCard {
}
class Deck implements List<Card>{
    + void shuffle()
    + Card draw()
}

class PlayerHand implements List<Card> {
    + void addCard(Card card)
    + void playCard(Card card)
}

@enduml